# Generated by Django 3.2.20 on 2025-05-21 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='amount',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Amount value of ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Input cooking time in minutes', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cooking time'),
        ),
    ]
