# Generated by Django 3.2.20 on 2025-05-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20250521_1609'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comment',
            name='unique_comment',
        ),
    ]
