# Generated by Django 3.2.20 on 2025-05-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, help_text='Ваш Telegram ID', max_length=100, null=True, verbose_name='Telegram ID'),
        ),
    ]
