# Generated by Django 3.2.20 on 2025-05-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_notify',
            field=models.BooleanField(default=False, help_text='Получать уведомления в Telegram', verbose_name='Уведомления в Telegram'),
        ),
    ]
