name: foodgram workflow

on: push

jobs:
  social_network_pytest:
    name: Запуск pytest в социальной сети
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: foodgram_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          cd social_network
          pip install -r requirements.txt
      - name: Запуск pytest
        env:
          SECRET_KEY: 'django-insecure-test-key-for-github-actions'
          DB_ENGINE: 'django.db.backends.postgresql'
          DB_NAME: 'foodgram_test'
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          DB_HOST: 'localhost'
          DB_PORT: '5432'
        run: |
          cd social_network
          pytest

  build_and_push_to_docker_hub:
    name: Сборка и пуш соц сети джанго
    runs-on: ubuntu-latest
    needs: social_network_pytest
    if: success()
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Собрать и пушнуть Социальную сеть
        uses: docker/build-push-action@v2 
        with:
          context: ./social_network
          file: ./social_network/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_social_network:latest 

  build_and_push_ai_backend:
    name: Сборка и пуш AI бэкенда
    runs-on: ubuntu-latest
    needs: social_network_pytest
    if: success()
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Собрать и пушнуть AI бэкенд
        uses: docker/build-push-action@v2
        with:
          context: ./social_network_ai_backend
          file: ./social_network_ai_backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_ai_backend:latest 
