name: foodgram workflow

on: push

jobs:
  social_network_pytest:
    name: Запуск pytest в социальной сети
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Запуск pytest
        run: |
          cd social_network
          pytest

  build_and_push_to_docker_hub:
    name: Сборка и пуш в Docker Hub
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Собрать и пушнуть Социальную сеть
        uses: docker/build-push-action@v2 
        with:
          context: ./social_network
          file: ./social_network/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/foodgram_social_network:latest 
